In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import numpy as np
import torch
import torch.nn as nn
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
import requests
from io import StringIO

In [3]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
ABBpath = '/content/drive/MyDrive/CPP-CSS/Stock_Market_Predictor/Datasets/raw-data/ABB-2021-04-08.csv'
df = pd.read_csv(ABBpath)

In [5]:
#df = pd.read_csv('D:/CPP-CSS/Stock_Market_Predictor/Datasets/raw-data/ABB-2021-03-12.csv')
#df['Date'] =pd.to_datetime(df.Date)
df = df.dropna()
df.reset_index(inplace=True, drop=True)
df.head()

Date   Open       High        Low      Close  Adj Close  Volume
0  2001-04-06  17.00  17.000000  16.781250  16.828125   8.432508  162100
1  2001-04-09  16.90  17.299999  16.900000  17.299999   8.668963   31300
2  2001-04-10  17.75  17.920000  17.700001  17.790001   8.914501   39500
3  2001-04-11  17.50  17.600000  17.400000  17.600000   8.819292   17900
4  2001-04-12  17.50  17.500000  17.400000  17.500000   8.769181   33000

In [6]:
MOVING_AVGS = [5,10,20,50,100,200]
DONCHIANS = [5,10,20,50,100,200]
TIME_LAGS = [1,2,3,4,5,6,7,8,9,10]
FORWARD_LAG = 5

# Generating Moving Averages

5, 10, 20, 50, 100, 200 days

In [7]:
for period in MOVING_AVGS:
    indicator_name = "SMA_%d" % (period)
    df[indicator_name] = df['Close'].rolling(period).mean()

# Bollinger Bands

- 20 periods, 2 standard deviations
- 20 periods, 1 standard deviation
- 10 periods, 1 standard deviation
- 20 periods, 2 standard deviations

In [8]:
df['BollingerBand_Up_20_2'] = df['Close'].rolling(20).mean() + 2*df['Close'].rolling(20).std()
df['BollingerBand_Down_20_2'] = df['Close'].rolling(20).mean() - 2*df['Close'].rolling(20).std()
df['BollingerBand_Up_20_1'] = df['Close'].rolling(20).mean() + df['Close'].rolling(20).std()
df['BollingerBand_Down_20_1'] = df['Close'].rolling(20).mean() - df['Close'].rolling(20).std()
df['BollingerBand_Up_10_1'] = df['Close'].rolling(10).mean() + df['Close'].rolling(10).std()
df['BollingerBand_Down_10_1'] = df['Close'].rolling(10).mean() - df['Close'].rolling(10).std()
df['BollingerBand_Up_10_2'] = df['Close'].rolling(10).mean() + 2*df['Close'].rolling(10).std()
df['BollingerBand_Down_10_2'] = df['Close'].rolling(10).mean() - 2*df['Close'].rolling(10).std()

# Donchian Channels

Same periods as moving average

In [9]:
for period in DONCHIANS:
    up_name = "Donchian_Channel_Up_%d" % (period)
    down_name = "Donchian_Channel_Down_%d" % (period)
    
    df[up_name] = df['High'].rolling(period).max()
    df[down_name] = df['Low'].rolling(period).min()

# Time Lags

Calculating a new dataset with various time lags.
This will enable the ability to define our target variable as the close price of X days in the future.

In [10]:
newdata = df['Close'].to_frame()
for lag in TIME_LAGS:
    shift = lag
    shifted = df.shift(shift)
    shifted.columns = [str.format("%s_shifted_by_%d" % (column ,shift)) for column in shifted.columns]
    newdata = pd.concat((newdata,shifted),axis=1)

In [11]:
newdata.head()

Close  ... Donchian_Channel_Down_200_shifted_by_10
0  16.828125  ...                                     NaN
1  17.299999  ...                                     NaN
2  17.790001  ...                                     NaN
3  17.600000  ...                                     NaN
4  17.500000  ...                                     NaN

[5 rows x 331 columns]

In [12]:
forward_lag = FORWARD_LAG
newdata['target'] = newdata['Close'].shift(-forward_lag)
newdata = newdata.drop('Close',axis=1)
newdata = newdata.dropna()
print(newdata.shape)
newdata.head()

(4818, 331)


Date_shifted_by_1  ...  target
209        2002-02-08  ...    7.25
210        2002-02-11  ...    7.15
211        2002-02-12  ...    6.99
212        2002-02-13  ...    6.95
213        2002-02-14  ...    6.60

[5 rows x 331 columns]

Our data is now 4818 rows x 331 columns

In [45]:
newdata.to_csv('/content/drive/MyDrive/CPP-CSS/Stock_Market_Predictor/Datasets/Input/ABBInput.csv', index=False)